name = "presigned-url-generator"
main = "src/worker.js"
compatibility_date = "2026-10-03"

[env.production]
routes = [
  { pattern = "https://hatedforever.com/api/*", zone_name = "hatedforever.com" }
]

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "site-imgs"

[env.production.vars]
CLOUDFLARE_ACCOUNT_ID = "59b89d4581327485a1dacac5550b88e1"
