-- Generated by: node pets/helpers/validate-egg.mjs curious-egg --sql
-- Needs someone with Supabase access to run it. hatch_pet reads "contents" from this row to roll the monster.
INSERT INTO shop_items (name, description, cost, category, metadata, image_url, active)
VALUES ('Curious Egg', 'A strange egg with some heft to it.', 999, 'pet_egg', '{"egg":"curious-egg","gen_version":1,"hatch":{"actions":["visit_calendar","visit_strategies","visit_roster","visit_loot","visit_guildbank","view_gallery","claim_sparkle","set_character_name","open_shop"],"distinct_actions":9},"contents":[{"monster":"baby","chance":100}],"xp_curve":[60,100,140,180,230,290],"skins":{"baby":[{"key":"toon","chance":1}]}}', 'pets/eggs/curious-egg/assets/shop.webp', true);
